[package]
name = "bleichenbacher-cca-poc"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
rsa = "0.9"
hex = "0.4"
tokio = { version = "1.40", features = ["rt-multi-thread", "macros"] }
futures = "0.3"
num_cpus = "1.16"
